#include "Payloads.h"

#include <dlfcn.h>

#include <openssl/evp.h> // TYPES ONLY - the EVP_* symbols are resolved via dlsym below,
                         // keeping them out of the import table

#include <cstring>

#include "payload_keys.h"
#include "ObfAnnotations.h" // generated by payload_packer at build time

// The blob objects are produced by `ld -r -b binary` over the packed .bin files
// (binutils names the symbols after the file: p0.bin -> _binary_p0_bin_*).
// Neutral file names on purpose - the symbol table must not advertise what is
// inside.
extern "C" const unsigned char _binary_p0bin_start[];
extern "C" const unsigned char _binary_p0bin_end[];
extern "C" const unsigned char _binary_p1bin_start[];
extern "C" const unsigned char _binary_p1bin_end[];
extern "C" const unsigned char _binary_p2bin_start[];
extern "C" const unsigned char _binary_p2bin_end[];
extern "C" const unsigned char _binary_p3bin_start[];
extern "C" const unsigned char _binary_p3bin_end[];

// Weak default definitions so a build without a given payload still links.
extern "C" const unsigned char _binary_p0bin_start[1] __attribute__((weak)) = {0};
extern "C" const unsigned char _binary_p0bin_end[1] __attribute__((weak)) = {0};
extern "C" const unsigned char _binary_p1bin_start[1] __attribute__((weak)) = {0};
extern "C" const unsigned char _binary_p1bin_end[1] __attribute__((weak)) = {0};
extern "C" const unsigned char _binary_p2bin_start[1] __attribute__((weak)) = {0};
extern "C" const unsigned char _binary_p2bin_end[1] __attribute__((weak)) = {0};
extern "C" const unsigned char _binary_p3bin_start[1] __attribute__((weak)) = {0};
extern "C" const unsigned char _binary_p3bin_end[1] __attribute__((weak)) = {0};

namespace payloads
{

namespace
{

enum class Which { Cs2 = 0, Tf2 = 1, SteamModule = 2, Injector = 3 };

struct Blob {
    const unsigned char* begin;
    const unsigned char* end;
};

[[nodiscard]] Blob blobFor(Which which) noexcept
{
    switch (which) {
    case Which::Cs2: return {_binary_p0bin_start, _binary_p0bin_end};
    case Which::Tf2: return {_binary_p1bin_start, _binary_p1bin_end};
    case Which::SteamModule: return {_binary_p2bin_start, _binary_p2bin_end};
    case Which::Injector: return {_binary_p3bin_start, _binary_p3bin_end};
    }
    return {nullptr, nullptr};
}

[[nodiscard]] QByteArray symmetricKey() noexcept
{
    QByteArray key(32, '\0');
    for (int i = 0; i < 32; ++i)
        key[i] = static_cast<char>(payload_keys::kSymKeyMasked[i] ^ payload_keys::kSymKeyMask[i]);
    return key;
}

[[nodiscard]] uint32_t readU32(const unsigned char* p) noexcept
{
    return static_cast<uint32_t>(p[0]) | (static_cast<uint32_t>(p[1]) << 8)
        | (static_cast<uint32_t>(p[2]) << 16) | (static_cast<uint32_t>(p[3]) << 24);
}

[[nodiscard]] uint64_t readU64(const unsigned char* p) noexcept
{
    uint64_t v = 0;
    for (int i = 7; i >= 0; --i)
        v = (v << 8) | p[i];
    return v;
}

// ---- runtime-resolved libcrypto -------------------------------------------------------
//
// NOT linked: the loader's import table carries no EVP_*/libcrypto references (a reverser
// reads imports first - the symbol names alone narrate "chacha payload + ed25519 sig").
// Resolved once via dlopen/dlsym; any failure = fail-closed.

// dlsym names are XOR-obfuscated at COMPILE time (pad 0x5A): otherwise the resolution
// strings ("EVP_DecryptInit_ex" ...) sit in .rodata and `strings` narrates the design
// even though the import table is clean. The literal exists only during consteval.
template <std::size_t N>
struct ObfName {
    char data[N];
    consteval ObfName(const char (&s)[N]) : data{}
    {
        for (std::size_t i = 0; i < N; ++i)
            data[i] = static_cast<char>(s[i] ^ 0x5A);
    }
    // asm-opaque + noinline like the module-side vaults: an inlined decode would let the
    // optimizer precompute the XOR and emit the plaintext as immediates again.
    __attribute__((noinline)) void decode(char* out) const noexcept
    {
        const char* p = data;
        asm volatile("" : "+r"(p));
        for (std::size_t i = 0; i < N; ++i)
            out[i] = static_cast<char>(p[i] ^ 0x5A);
    }
};

// obfuscated dlsym names (compile-time XOR of the literals)
constexpr ObfName kNameCtxNew{"EVP_CIPHER_CTX_new"};
constexpr ObfName kNameCtxFree{"EVP_CIPHER_CTX_free"};
constexpr ObfName kNameAead{"EVP_chacha20_poly1305"};
constexpr ObfName kNameDecryptInit{"EVP_DecryptInit_ex"};
constexpr ObfName kNameDecryptUpdate{"EVP_DecryptUpdate"};
constexpr ObfName kNameDecryptFinal{"EVP_DecryptFinal_ex"};
constexpr ObfName kNameCtxCtrl{"EVP_CIPHER_CTX_ctrl"};
constexpr ObfName kNameMdCtxNew{"EVP_MD_CTX_new"};
constexpr ObfName kNameMdCtxFree{"EVP_MD_CTX_free"};
constexpr ObfName kNameVerifyInit{"EVP_DigestVerifyInit"};
constexpr ObfName kNameVerify{"EVP_DigestVerify"};
constexpr ObfName kNamePkeyNew{"EVP_PKEY_new_raw_public_key"};
constexpr ObfName kNamePkeyFree{"EVP_PKEY_free"};

// type-erased entry: the dispatcher keeps the per-name template argument alive
struct Entry {
    const void* name;
    void (*decode)(const void*, char*);
    void** target;
};

template <std::size_t N>
void decodeObf(const void* name, char* out)
{
    static_cast<const ObfName<N>*>(name)->decode(out);
}

template <std::size_t N>
constexpr Entry makeEntry(const ObfName<N>& name, void** target)
{
    return {&name, &decodeObf<N>, target};
}

struct Crypto {
    EVP_CIPHER_CTX* (*ctxNew)();
    void (*ctxFree)(EVP_CIPHER_CTX*);
    const EVP_CIPHER* (*aeadCipher)();
    int (*decryptInit)(EVP_CIPHER_CTX*, const EVP_CIPHER*, void*, const unsigned char*, const unsigned char*);
    int (*decryptUpdate)(EVP_CIPHER_CTX*, unsigned char*, int*, const unsigned char*, int);
    int (*decryptFinal)(EVP_CIPHER_CTX*, unsigned char*, int*);
    int (*ctxCtrl)(EVP_CIPHER_CTX*, int, int, void*);
    EVP_MD_CTX* (*mdCtxNew)();
    void (*mdCtxFree)(EVP_MD_CTX*);
    int (*verifyInit)(EVP_MD_CTX*, void*, const EVP_MD*, void*, EVP_PKEY*);
    int (*verify)(EVP_MD_CTX*, const unsigned char*, size_t, const unsigned char*, size_t);
    EVP_PKEY* (*pkeyRawPublic)(int, void*, const unsigned char*, size_t);
    void (*pkeyFree)(EVP_PKEY*);
};

[[nodiscard]] const Crypto* crypto()
{
    static Crypto table;
    static bool resolved = false;
    if (resolved)
        return table.ctxNew ? &table : nullptr;
    resolved = true;

    void* h = dlopen("libcrypto.so.3", RTLD_NOW | RTLD_LOCAL);
    if (!h)
        h = dlopen("libcrypto.so.1.1", RTLD_NOW | RTLD_LOCAL);
    if (!h)
        h = dlopen("libcrypto.so", RTLD_NOW | RTLD_LOCAL);
    if (!h)
        return nullptr;

    static const Entry entries[] = {
        makeEntry(kNameCtxNew, reinterpret_cast<void**>(&table.ctxNew)),
        makeEntry(kNameCtxFree, reinterpret_cast<void**>(&table.ctxFree)),
        makeEntry(kNameAead, reinterpret_cast<void**>(&table.aeadCipher)),
        makeEntry(kNameDecryptInit, reinterpret_cast<void**>(&table.decryptInit)),
        makeEntry(kNameDecryptUpdate, reinterpret_cast<void**>(&table.decryptUpdate)),
        makeEntry(kNameDecryptFinal, reinterpret_cast<void**>(&table.decryptFinal)),
        makeEntry(kNameCtxCtrl, reinterpret_cast<void**>(&table.ctxCtrl)),
        makeEntry(kNameMdCtxNew, reinterpret_cast<void**>(&table.mdCtxNew)),
        makeEntry(kNameMdCtxFree, reinterpret_cast<void**>(&table.mdCtxFree)),
        makeEntry(kNameVerifyInit, reinterpret_cast<void**>(&table.verifyInit)),
        makeEntry(kNameVerify, reinterpret_cast<void**>(&table.verify)),
        makeEntry(kNamePkeyNew, reinterpret_cast<void**>(&table.pkeyRawPublic)),
        makeEntry(kNamePkeyFree, reinterpret_cast<void**>(&table.pkeyFree)),
    };
    for (const auto& e : entries) {
        char name[40];
        e.decode(e.name, name);
        *e.target = dlsym(h, name);
        std::memset(name, 0, sizeof(name));
        if (!*e.target)
            return nullptr;
    }
    return &table;
}

// "NSPX" XOR-obfuscated (pad 0x5A) so the container magic is not a literal in the binary.
constexpr unsigned char kMagicObf[4] = {0x14, 0x09, 0x0A, 0x02}; // 'N','S','P','X' ^ 0x5A

struct Parsed {
    const unsigned char* header = nullptr;  // AAD range begin
    qsizetype headerLen = 0;
    const unsigned char* nonce = nullptr;
    const unsigned char* ciphertext = nullptr;
    qint64 ctLen = 0;
    qint64 plainLen = 0;
};

// Parses + Ed25519-verifies a container. Returns an empty optional-ish struct on failure
// (error set). The signature covers header+nonce+ciphertext, so after this returns true
// the ciphertext is authenticated and safe to stream.
[[nodiscard]] bool parseAndVerify(Which which, const char* expectedName, Parsed &out, QString *error)
{
    const Blob blob = blobFor(which);
    const qsizetype size = blob.end - blob.begin;
    if (size <= 4) {
        if (error)
            *error = QStringLiteral("payload not embedded in this build");
        return false;
    }

    const unsigned char* p = blob.begin;
    unsigned char magic[4];
    for (int i = 0; i < 4; ++i)
        magic[i] = static_cast<unsigned char>(kMagicObf[i] ^ 0x5A);
    if (std::memcmp(p, magic, 4) != 0) {
        if (error)
            *error = QStringLiteral("payload magic mismatch");
        return false;
    }
    p += 4;
    if (readU32(p) != 1) {
        if (error)
            *error = QStringLiteral("unsupported payload version");
        return false;
    }
    p += 4;

    const uint32_t nameLen = readU32(p);
    p += 4;
    if (nameLen == 0 || size < qsizetype(8 + nameLen + 16 + 8 + 12 + 16 + 64)) {
        if (error)
            *error = QStringLiteral("payload header truncated");
        return false;
    }
    if (std::memcmp(p, expectedName, nameLen) != 0) {
        if (error)
            *error = QStringLiteral("payload name mismatch");
        return false;
    }
    p += nameLen;

    const uint64_t ctLen = readU64(p);
    p += 8;
    const uint64_t plainLen = readU64(p);
    p += 8;
    if (ctLen < 16 || ctLen != plainLen + 16
        || size != qsizetype((p - blob.begin) + 12 + ctLen + 64)) {
        if (error)
            *error = QStringLiteral("payload length mismatch");
        return false;
    }

    const unsigned char* nonce = p;
    p += 12;
    const unsigned char* ciphertext = p;
    const unsigned char* sig = ciphertext + ctLen;

    // Ed25519 signature over everything before the signature (fail-closed: a tampered or
    // foreign payload never decrypts).
    const Crypto* c = crypto();
    if (!c) {
        if (error)
            *error = QStringLiteral("crypto backend unavailable");
        return false;
    }
    EVP_MD_CTX* md = c->mdCtxNew();
    EVP_PKEY* pub = c->pkeyRawPublic(EVP_PKEY_ED25519, nullptr,
        payload_keys::kEd25519Public, sizeof(payload_keys::kEd25519Public));
    bool sigOk = md && pub
        && c->verifyInit(md, nullptr, nullptr, nullptr, pub) == 1
        && c->verify(md, sig, 64, blob.begin, static_cast<size_t>(sig - blob.begin)) == 1;
    c->mdCtxFree(md);
    c->pkeyFree(pub);
    if (!sigOk) {
        if (error)
            *error = QStringLiteral("payload signature verification failed");
        return false;
    }

    out.header = blob.begin;
    out.headerLen = nonce - blob.begin;
    out.nonce = nonce;
    out.ciphertext = ciphertext;
    out.ctLen = static_cast<qint64>(ctLen);
    out.plainLen = static_cast<qint64>(plainLen);
    return true;
}

// AEAD-decrypts a single whole buffer (whole-container path for the small payloads and
// the gdb fallbacks). Tag = last 16 bytes of ciphertext.
[[nodiscard]] NS_OBF_FLATTEN NS_OBF_ICALL bool decryptWhole(const Parsed &parsed, QByteArray &plain, QString *error)
{
    const Crypto* c = crypto();
    if (!c) {
        if (error)
            *error = QStringLiteral("crypto backend unavailable");
        return false;
    }
    plain.resize(qsizetype(parsed.plainLen));
    EVP_CIPHER_CTX* ctx = c->ctxNew();
    QByteArray key = symmetricKey();
    int len = 0;
    bool ok = ctx
        && c->decryptInit(ctx, c->aeadCipher(), nullptr,
               reinterpret_cast<const unsigned char*>(key.constData()), parsed.nonce) == 1
        && c->decryptUpdate(ctx, nullptr, &len, parsed.header, int(parsed.headerLen)) == 1;
    if (parsed.plainLen > 0) {
        ok = ok
            && c->decryptUpdate(ctx, reinterpret_cast<unsigned char*>(plain.data()), &len,
                   parsed.ciphertext, int(parsed.plainLen)) == 1;
    }
    if (ok && c->ctxCtrl(ctx, EVP_CTRL_AEAD_SET_TAG, 16,
            const_cast<unsigned char*>(parsed.ciphertext + parsed.plainLen)) == 1) {
        unsigned char dummy[16];
        ok = c->decryptFinal(ctx, dummy, &len) == 1;
    }
    c->ctxFree(ctx);
    if (!ok) {
        if (error)
            *error = QStringLiteral("payload decryption failed (tampered?)");
        return false;
    }
    return true;
}

} // namespace

bool hasCs2() { return blobFor(Which::Cs2).end > blobFor(Which::Cs2).begin + 1; }
bool hasTf2() { return blobFor(Which::Tf2).end > blobFor(Which::Tf2).begin + 1; }
bool hasSteamModule() { return blobFor(Which::SteamModule).end > blobFor(Which::SteamModule).begin + 1; }
bool hasInjector() { return blobFor(Which::Injector).end > blobFor(Which::Injector).begin + 1; }

namespace
{

[[nodiscard]] NS_OBF_FLATTEN NS_OBF_ICALL QByteArray extractOne(Which which, const char* expectedName, QString *error)
{
    Parsed parsed;
    if (!parseAndVerify(which, expectedName, parsed, error))
        return {};
    QByteArray plain;
    if (!decryptWhole(parsed, plain, error))
        return {};
    return plain;
}

} // namespace

QByteArray extractCs2(QString *error) { return extractOne(Which::Cs2, "cs2", error); }
QByteArray extractTf2(QString *error) { return extractOne(Which::Tf2, "tf2", error); }
QByteArray extractSteamModule(QString *error) { return extractOne(Which::SteamModule, "steam", error); }
QByteArray extractInjector(QString *error) { return extractOne(Which::Injector, "injector", error); }

// ---- streaming ------------------------------------------------------------------------

PayloadStream::~PayloadStream()
{
    if (m_ctx) {
        if (const Crypto* c = crypto())
            c->ctxFree(static_cast<EVP_CIPHER_CTX*>(m_ctx));
        m_ctx = nullptr;
    }
}

void StreamDeleter::operator()(PayloadStream *s) const noexcept { delete s; }

namespace
{
[[nodiscard]] NS_OBF_FLATTEN NS_OBF_ICALL StreamPtr openStream(Which which, const char* expectedName, QString *error)
{
    const Crypto* c = crypto();
    if (!c) {
        if (error)
            *error = QStringLiteral("crypto backend unavailable");
        return {};
    }
    Parsed parsed;
    if (!parseAndVerify(which, expectedName, parsed, error))
        return {};

    EVP_CIPHER_CTX* ctx = c->ctxNew();
    QByteArray key = symmetricKey();
    int len = 0;
    bool ok = ctx
        && c->decryptInit(ctx, c->aeadCipher(), nullptr,
               reinterpret_cast<const unsigned char*>(key.constData()), parsed.nonce) == 1
        && c->decryptUpdate(ctx, nullptr, &len, parsed.header, int(parsed.headerLen)) == 1;
    if (!ok) {
        if (ctx)
            c->ctxFree(ctx);
        if (error)
            *error = QStringLiteral("payload decrypt init failed");
        return {};
    }

    auto stream = StreamPtr(new PayloadStream());
    stream->m_ctx = ctx;
    stream->m_ciphertext = parsed.ciphertext;
    stream->m_ctRemaining = parsed.ctLen - 16; // the last 16 bytes are the Poly1305 tag
    stream->m_plainLen = parsed.plainLen;
    return stream;
}
} // namespace

StreamPtr openCs2Stream(QString *error) { return openStream(Which::Cs2, "cs2", error); }
StreamPtr openTf2Stream(QString *error) { return openStream(Which::Tf2, "tf2", error); }
StreamPtr openSteamStream(QString *error) { return openStream(Which::SteamModule, "steam", error); }

NS_OBF_FLATTEN bool PayloadStream::nextChunk(QByteArray &out, QString *error)
{
    out.clear();
    if (m_finished || !m_ctx) {
        // normal exhaustion - only real failures set an error
        return false;
    }

    const Crypto* c = crypto();
    if (!c) {
        if (error)
            *error = QStringLiteral("crypto backend unavailable");
        return false;
    }

    // 64 KB chunks keep the plaintext footprint bounded (no full module image in memory)
    constexpr qint64 kChunk = 64 * 1024;
    const qint64 take = m_ctRemaining < kChunk ? m_ctRemaining : kChunk;
    const int before = out.size();
    out.resize(before + int(take));
    int len = 0;
    if (take > 0
        && c->decryptUpdate(static_cast<EVP_CIPHER_CTX*>(m_ctx),
               reinterpret_cast<unsigned char*>(out.data()) + before, &len,
               m_ciphertext, int(take)) != 1) {
        if (error)
            *error = QStringLiteral("payload decrypt failed");
        m_finished = true;
        out.clear();
        return false;
    }
    m_ciphertext += take;
    m_ctRemaining -= take;
    m_plainProduced += len;

    if (m_ctRemaining == 0) {
        // final: verify the tag (the Ed25519 signature already proved the ciphertext, so
        // this is belt-and-suspenders)
        unsigned char dummy[16];
        if (c->ctxCtrl(static_cast<EVP_CIPHER_CTX*>(m_ctx), EVP_CTRL_AEAD_SET_TAG, 16,
                const_cast<unsigned char*>(m_ciphertext)) != 1
            || c->decryptFinal(static_cast<EVP_CIPHER_CTX*>(m_ctx), dummy, &len) != 1) {
            if (error)
                *error = QStringLiteral("payload tag check failed");
            m_finished = true;
            out.clear();
            return false;
        }
        m_finished = true;
        return !out.isEmpty(); // a trailing empty final chunk is a normal end-of-stream
    }
    return true;
}

} // namespace payloads
