#pragma once

#include <QByteArray>
#include <QCoreApplication>
#include <QFile>

#include <cstring>

#include "payload_keys.h"
#include "ObfAnnotations.h" // generated by payload_packer at build time

// Session binding trailer ("the handshake stamp").
//
// EVERY module the loader injects (CS2, TF2, Steam module - memfd stdin path AND the gdb
// fallback temp copies) gets 64 bytes appended AFTER its ELF image. dlopen ignores trailing
// bytes; the module re-opens its own memfd and verifies the trailer at init:
//
//   offset 0   "NSHB02"          6B magic
//   offset 6   u8 pad[2]
//   offset 8   u64 loaderPid     (little-endian)
//   offset 16  u8 loaderComm[16] (THIS loader's runtime /proc/self/comm, NUL-padded)
//   offset 32  u8 proof[32]      loaderComm-block XOR heartbeatKey XOR targetPid
//
// 2026-09-24 hardening: the proof also mixes the TARGET pid the module is being injected
// into. The module recomputes the mix with its own getpid(), so a memfd file copied out of
// a live session (cp /proc/<pid>/fd/<n> - module bytes AND trailer together) is bricked
// when re-injected into any other process: the old trailer's pid no longer matches. Before
// this, the copy carried a VALID trailer (comm + key are attacker-knowable) and passed the
// module's verification - the fd-copy dump was the one-command crack.
//
// What this buys:
//  - A module stripped from a dump and re-injected by ANY other injector has no trailer ->
//    fails closed (inert / self-unload). Redistribution of the bare .so is bricked.
//  - A loader killed after injection is noticed by the module's liveness tick (loader pid
//    from the trailer) -> the module releases itself after a grace period.
//  - The liveness check is NAME-FREE: the module compares /proc/<loaderPid>/comm against the
//    comm stamped HERE (read from the running loader at stamp time), so the loader binary
//    can be renamed/repackaged by whoever ships it without breaking session binding - and
//    no loader name is hardcoded in any module. (v1 hardcoded "Loader" and silently
//    released the module ~5 minutes after injection whenever the binary was named
//    anything else - the 2026-09-22 friend-machine uninject bug.)
//  - proof XOR construction (instead of HMAC): the module has no crypto under -nostdlib,
//    and the attacker model this control targets (module bytes WITHOUT a loader) never
//    sees a valid trailer to learn the key from. XOR proof is unforgeable there; replay
//    of a stolen game-process memfd (module+trailer together) is handled by the liveness
//    check, not by the proof.
namespace session_trailer
{

constexpr qsizetype kSize = 64;

[[nodiscard]] inline QByteArray heartbeatKey()
{
    QByteArray key(32, '\0');
    for (int i = 0; i < 32; ++i)
        key[i] = static_cast<char>(payload_keys::kHeartbeatKeyMasked[i] ^ payload_keys::kHeartbeatKeyMask[i]);
    return key;
}

// Returns the full trailer; commOut (optional) receives the loader comm block that was
// stamped (for logging).
[[nodiscard]] inline NS_OBF_FLATTEN QByteArray build(qint64 loaderPid, qint64 targetPid, QByteArray *commOut = nullptr)
{
    QByteArray trailer(kSize, '\0');
    auto* t = reinterpret_cast<unsigned char*>(trailer.data());
    std::memcpy(t, "NSHB02", 6);

    const unsigned long long pid = static_cast<unsigned long long>(loaderPid);
    for (int i = 0; i < 8; ++i)
        t[8 + i] = static_cast<unsigned char>((pid >> (8 * i)) & 0xff);

    // /proc/self/comm: the kernel's own view of this process name (basename of the executed
    // binary, truncated to 15 chars + NUL by TASK_COMM_LEN). Read at STAMP time so the
    // trailer always matches whatever name the loader binary carries.
    QByteArray comm(16, '\0');
    if (QFile commFile(QStringLiteral("/proc/self/comm")); commFile.open(QIODevice::ReadOnly)) {
        QByteArray name = commFile.readAll();
        while (!name.isEmpty() && (name.back() == '\n' || name.back() == '\r'))
            name.chop(1);
        if (name.size() > 15)
            name.truncate(15);
        std::memcpy(comm.data(), name.constData(), static_cast<std::size_t>(name.size()));
    }
    std::memcpy(t + 16, comm.constData(), 16);
    if (commOut)
        *commOut = comm;

    const unsigned long long target = static_cast<unsigned long long>(targetPid);
    const QByteArray key = heartbeatKey();
    for (int i = 0; i < 32; ++i) {
        const auto targetByte = static_cast<unsigned char>((target >> ((i % 8) * 8)) & 0xff);
        t[32 + i] = static_cast<unsigned char>(comm[i % 16] ^ key[i] ^ targetByte);
    }
    return trailer;
}

// Loader-side helper: appends the trailer to a decrypted payload (stdin stream or the
// gdb fallback temp copy).
[[nodiscard]] inline QByteArray stamped(const QByteArray &payload, qint64 targetPid)
{
    QByteArray out = payload;
    out.append(build(QCoreApplication::applicationPid(), targetPid));
    return out;
}

} // namespace session_trailer
